#!/bin/bash
set -e

GITREF=$1

apt-get install -y python-dev libxml2-dev libmysqlclient-dev libxslt1-dev libpq-dev zlib1g-dev python-gdbm

git clone https://github.com/openstack/cinder
cd cinder
git checkout $GITREF

# Not sure if there's an advantage to using a venv here, since we've got the
# filesystem to ourselves thanks to docker...
virtualenv cinder-venv
. ./cinder-venv/bin/activate

pip install --upgrade pip
pip install -r requirements.txt

pip install --upgrade tox

python setup.py develop

tox -egenconfig
cp etc/cinder/cinder.conf.sample /etc/cinder/cinder.conf
cp etc/cinder/api-paste.ini /etc/cinder/
cp etc/cinder/policy.json /etc/cinder/
cp etc/cinder/rootwrap.conf /etc/cinder/
cp -r etc/cinder/rootwrap.d /etc/cinder/

